spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SECURITY_GOOGLE_CLIENT_ID}
            client-secret: ${SECURITY_GOOGLE_CLIENT_SECRET}
  datasource:
    url: jdbc:h2:./database
    username: sa
    password: sa
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 3MB
logging:
  level:
    org:
      springframework:
        security: INFO
        jdbc: DEBUG
smart-collections:
  file-upload:
    storage: ./storage