name: Deploy to UAT
on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        required: true

jobs:
  deploy:
    name: Deploy to UAT
    runs-on: ubuntu-latest

    environment:
      name: Development

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.release }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.2'

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.3.0

      - name: Cache backend dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-composer
        with: 
          path: ./backend/vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache frontend dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build the bundle
        run: ./.github/workflows/deploy_dev/run_build.sh
        
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          exclude: |
            **/.devcontainer/**
            **/tests/**
            .env.example
            .env.testing