name: Deploy to dev
on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        required: true

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.release }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.2'
            
