name: Build a PR

on:
  pull_request:
    branches: 
     - 'dev'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    name: Build Backend

    strategy:
      matrix:
        php_version: ['8.1', '8.2']

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: ${{ matrix.php_version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-composer
        with: 
          path: ./backend/vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
              
      - name: Install dependencies
        run: cd ./backend && composer install

      - name: Run migrations for tests
        run: |
          cd ./backend
          touch test_database.sqlite
          touch .env.testing
          echo "DB_CONNECTION=sqlite" >> .env.testing
          echo "DB_DATABASE=$(pwd)/test_database.sqlite" >> .env.testing
          echo "APP_KEY=" >> .env.testing
          
          php artisan key:generate --env=testing
          php artisan --env=testing migrate

      - name: Build frontend
        run: |
          cd ./backend
          npm install
          npm run build

      - name: Run tests
        run: cd ./backend && php artisan test