name: Build the branch

on:
  pull_request:
    branches: 
     - 'dev'

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.2'

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-composer
        with: 
          path: ~/backend/vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
              
      - name: Install dependencies
        run: cd ./backend && composer install

      - name: Run migrations for tests
        run: |
          cd ./backend
          touch test_database.sqlite
          touch .env.testing
          echo "DB_CONNECTION=sqlite" >> .env.testing
          echo "DB_DATABASE=$(pwd)/test_database.sqlite" >> .env.testing
          php artisan --env=testing migrate

      - name: Run tests
        run: cd ./backend && php artisan test

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.3.0

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
              
      - name: Install dependencies
        run: cd ./frontend && npm install
      
      - name: Run tests
        run: cd ./frontend && npm run test --passWithNoTests

      - name: Build frontend
        run: cd ./frontend && npm run build