name: Build a PR

on:
  pull_request:
    branches: 
     - 'dev'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    name: Build Backend

    strategy:
      matrix:
        php_version: ['8.1', '8.2']

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: vinyl
          MYSQL_USER: vinyl
          MYSQL_PASSWORD: vinyl

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: ${{ matrix.php_version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-composer
        with: 
          path: ./vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
              
      - name: Install dependencies
        run: composer install

      - name: Run migrations for tests
        run: |
          touch .env.testing
          echo "DB_CONNECTION=mysql" >> .env.testing
          echo "DB_HOST=mysql" >> .env.testing
          echo "DB_PORT=3306" >> .env.testing
          echo "DB_DATABASE=vinyl" >> .env.testing
          echo "DB_USERNAME=vinyl" >> .env.testing
          echo "DB_PASSWORD=vinyl" >> .env.testing
          echo "APP_KEY=" >> .env.testing
          
          php artisan key:generate --env=testing
          php artisan --env=testing migrate

      - name: Build frontend
        run: |
          npm install
          npm run build

      - name: Run tests
        run: php artisan test