name: Check PR Labels

on:
  pull_request:
    branches: 
     - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR labels
      run: |
        PR_REF=$GITHUB_REF
        PR_ID=$(echo $PR_REF | cut -d '/' -f 3)
        if [ -z "$PR_ID" ]
        then
          echo "PR ID is not available, exiting"
          exit 1
        fi

        gh pr view $PR_ID

        exit 0   
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF: ${{ vars.GITHUB_REF }}