name: Check PR Labels

on:
  pull_request:
    types:
      - labeled
      - unlabeled
    branches: 
     - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR labels
      run: |
        PR_REF=$GITHUB_REF
        PR_ID=$(echo $PR_REF | cut -d '/' -f 3)
        if [ -z "$PR_ID" ]
        then
          echo "PR ID is not available, exiting"
          exit 1
        fi

        LABELS=$(gh pr view $PR_ID --repo "$PR_OWNER/$PR_REPO" --json labels --jq '.labels[].name')
        ALLOWED_LABELS=(minor major patch)
        HAS_ONE=False

        for LABEL in ${LABELS[@]}
        do
          for ALLOWED in ${ALLOWED_LABELS[@]}
          do
            if [ $LABEL == $ALLOWED ]
            then
              if [ $HAS_ONE == False ]
              then
                HAS_ONE=True
              else
                echo "More than one label is assigned"
                echo "Has labels: $LABELS"
                exit 1
              fi
            fi
          done
        done

        if [ $HAS_ONE == False ]
        then
          echo "No mandatory labels assigned"
          echo "Has labels: $LABELS"
          exit 1
        fi

        exit 0   
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF: ${{ vars.GITHUB_REF }}
        PR_REPO: ${{ github.event.repository.name }}
        PR_OWNER: ${{ github.repository_owner }}