name: Check PR Labels

on:
  pull_request:
    branches: 
     - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR labels
      run: echo "1234"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      