name: On PR merge to DEV

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        default: "dev"
        description: "Branch for debugging purproses"
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  release_create:
    name: Create a new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Perform a release
        run: cd ./.github/workflows/pr_merge_dev && ./run.sh
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_BRANCH: "create-backend"