name: On PR merge to DEV

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        default: "dev"
        description: "Branch for debugging purproses"
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  release_create:
    name: Create a new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Perform a release
        run: |
          set -x
          python3 -h
          python -h
          COMMIT_MSG="Test commit (#2)"
          PR_ID=$(echo "${COMMIT_MSG}" | grep -Eo '#\d+' | grep -Eo '\d+')
        
          if [ -z "$PR_ID" ]
          then
            echo "PR ID is not included into the latest commit subject"
            exit 1
          fi
        
          echo "Latest PR is $PR_ID"